### ISSUE TITLE
Update Google Maps icon

### ISSUE THREAD

**Issue by Brottweiler** [natewren/moonshine-iconpack#3]
Since the new Google logo change the Google Maps icon doesn't match the new "G". 

Might also want to add an icon for [Google Street View](https://play.google.com/store/apps/details?id=com.google.android.street) since it is its own app now.

**Comment by kmark** [comment]
The current Google Maps icon is pretty close to the Moonshine style so what I've done is just defaulted to the builtin Maps icon. I know at least Nova Launcher is capable of this per app  substitution.

**Comment by pedropeguerojr** [comment]
We are working on updating all Google apps to the new logo. Thanks for your patience!
